### ISSUE TITLE
parfile reader does not recognise the MTOT parameter from DDGR model

### ISSUE THREAD

**Issue by chiamintan** [emmanuelfonseca/PSRpy#15]
Here is the specific error : 
```
Traceback (most recent call last):
  File "/Users/CM/anaconda3/bin/compute_grid_Shapiro.py", line 310, in <module>
    input_par.read(inpar)
  File "/Users/CM/anaconda3/lib/python3.7/site-packages/PSRpy/parfile/readpar.py", line 163, in read
    current_dict = getattr(self, parname)
AttributeError: 'Parfile' object has no attribute 'MTOT'
```

**Comment by emmanuelfonseca** [comment]
@chiamintan try it out now; here's what my latest patch looks like:

``` python
efonseca > $ python
Python 3.7.3 (default, Oct 27 2020, 17:27:46) 
[Clang 11.0.0 (clang-1100.0.33.12)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PSRpy.parfile import Parfile
>>> par = Parfile()
>>> par.read("B1534+12.current.DDGR.noASP.par")
>>> par.MTOT
{'value': 2.678468, 'flag': 1, 'error': 4e-06}
```

**Comment by chiamintan** [comment]
`compute_shapiro_grid.py` didn't parse the properties properly : 
```
Traceback (most recent call last):
  File "/Users/CM/anaconda3/bin/compute_grid_Shapiro.py", line 506, in <module>
    print("Fixing MTOT (best-fit = {0:.5f})...".format(input_par.MTOT))
TypeError: unsupported format string passed to dict.__format__
```

**Comment by chiamintan** [comment]
might be just the print statement

**Comment by emmanuelfonseca** [comment]
@chiamintan pull again and try now; part of the issue is the print statement, but i also needed to add a few lines to set `MTOT`. the script now works for me on non-CHIME data i have for `B1534+12`.

**Comment by chiamintan** [comment]
seems to work now, although I don't think there is a script to plot the distribution of masses from a M1-M2 shapiro delay grid
